name: Build & Publish Image

on:
  push:
    branches:
      - staging

env:
  # TODO: Change variable to your image's name.
  IMAGE_ID: ghcr.io/ariento89/digirent-nginx
  PAT: ${{ secrets.PAT }}
  API_URL: ${{ secrets.API_URL }}
  GITHUB_USERNAME: ariento89

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
  
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg API_URL=$API_URL -t $IMAGE_ID .

      - name: Log into registry
        run: docker login ghcr.io -u $GITHUB_USERNAME --password $PAT

      - name: Push image
        run: |
          # Tag docker image with version
          docker tag $IMAGE_ID $IMAGE_ID:staging

          # Push image to github container registry
          docker push $IMAGE_ID:staging
